simple_ga4:
  target: prod
  outputs:
    prod:
      dataset: prod
      fixed_retries: 2
      location: US
      priority: interactive
      project: <INSERT YOUR GOOGLE CLOUD PROJECT HERE>
      threads: 8
      job_execution_timeout_seconds: 900
      type: bigquery
      method: oauth
